apiVersion: v1
kind: PersistentVolume
metadata:
  name: soulbot-pv
spec:
  capacity:
    storage: 1Gi # Specify the desired storage capacity
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce # Access mode for a single node
  persistentVolumeReclaimPolicy: Delete # What to do with data when PV is deleted
  storageClassName: manual
  hostPath:
    path: /data/my-app # Replace with the actual path on the host
