apiVersion: apps/v1
kind: Deployment
metadata:
  name: soulbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: soulbot
  template:
    metadata:
      labels:
        app: soulbot
    spec:
      containers:
      - name: soulbot
        image: unprofessional/soulbot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80  # HTTP
        # - containerPort: 443 # HTTPS
        # only uncomment above if using soulbot-ingress.yaml service as a
        # Kubernetes ingress controller
        env:
        - name: DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: discord-bot-secret
              key: DISCORD_BOT_TOKEN
        - name: STORE_PATH
          value: "/data"
        - name: GUILD_STORE_FILE
          value: "guild.store.json"
        - name: CHANNEL_STORE_FILE
          value: "channel.store.json"
        - name: MEMBER_STORE_FILE
          value: "member.store.json"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: soulbot-pvc