apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: soulbot-pvc
spec:
  accessModes:
    - ReadWriteMany # Must match the PV's access mode
  storageClassName: manual # Should match the PV's storageClassName
  resources:
    requests:
      storage: 1Gi # Requested storage capacity, should match the PV's capacity
