# name: Deployment Pipeline

# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#   release:
#     types:
#       - created

# jobs:
#   soulbot_master_updated:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Soulbot Master Updated
#         env:
#           JENKINS_AUTH_TOKEN: ${{ secrets.JENKINS_AUTH_TOKEN }}
#         run: |
#           curl -X POST \
#             -u rally:$JENKINS_AUTH_TOKEN \
#             "https://shinralabs.ddns.net/buildByToken/buildWithParameters?job=soulbot_master_updated&token=your-job-token&PARAM_NAME=PARAM_VALUE"
